/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_winton_demo_JNIUtils.h"

/*
 * Class:     com_winton_demo_JNIUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
jstring JNICALL Java_com_winton_demo_JNIUtils_getStringFromNative
  (JNIEnv * env, jobject){
        return (*env).NewStringUTF("Hello JNI!");
  }

/*
 * Class:     com_winton_demo_JNIUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
jstring JNICALL Java_com_winton_demo_JNIUtils_getStringFromC
  (JNIEnv * env, jobject){
        return (*env).NewStringUTF("Hello JNI!");
  }
