/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_winton_demo_JNIUtils */

#ifndef _Included_com_winton_demo_JNIUtils
#define _Included_com_winton_demo_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_winton_demo_JNIUtils
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_winton_demo_JNIUtils_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_winton_demo_JNIUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_winton_demo_JNIUtils_getStringFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
