/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_winton_demo_JNIDemo */

#ifndef _Included_com_winton_demo_JNIDemo
#define _Included_com_winton_demo_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_winton_demo_JNIDemo
 * Method:    doNative
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_winton_demo_JNIDemo_doNative
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
